from pydantic import BaseModel, Field
from typing import List, Optional

class SpecialistOutput(BaseModel):
    """Output from a specialist agent tool."""
    content: str = Field(..., description="The content generated by the specialist agent, written in markdown.")
    sources: Optional[List[str]] = Field(None, description="A list of sources used by the specialist agent.")

class ResearchReport(BaseModel):
    """A conceptual model for a research report."""
    title: str = Field(..., description="The title of the report.")
    introduction: str = Field(..., description="An introduction to the topic.")
    body: str = Field(..., description="The main content of the report, with detailed analysis.")
    conclusion: str = Field(..., description="The conclusion summarizing the findings.")
    sources: Optional[List[str]] = Field(None, description="A list of sources used for the report.") 